### PR TITLE
Fix: Issue #1

### PR DESCRIPTION
**Pull request by katekyy**
Fixed compatibility issue, **but it needs to be checked by someone that have LID0 directory!**

### CODE REVIEW

**Review by eliasjonsson023 — CHANGES_REQUESTED** [review]
Thank you for improving this software. However, I'm afraid that I have to tell you that it didn't work as expected. Got the following error message when trying to run application:

thread 'main' panicked at 'Unable to read file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:20:74
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

and by the way, I have LID0 in my system.

**Comment by katekyy** [comment]
Hi! I think that I fixed it now.

**Comment by katekyy** [comment]
Hi! I think I fixed it now.

**Comment by katekyy** [comment]
Hi! I removed the debug output, think it's ready to be merged.

**Comment by eliasjonsson023** [comment]
Your branch was tested and it was confirmed that it works. Your branch was merged. Thank you for your contribution!

**Pull request merged**
